### ISSUE TITLE
Questions about serverless.yml

### ISSUE THREAD

**Issue by jackbillstrom** [erezrokah/lighthouse-layer#3]
Hi, AWS is quite new to me. Been struggling a lot with running Lighthouse as a Google Cloud Function.

Now that's out of the picture, but trying out your solution is very exciting for me.

However, I have some questions about this part on your blog post:
`Here are the relevant parts of my serverless.yml file:`
That link to the blob-commit isn't working.

I'd gladly wonder how set up `serverless.yml`

Could you post a more detailed `serverless.yml` or in better detail describe the step when you wrote:

>Notice I’m putting the Lambda behind an SQS queue to throttle it. I’m using a plugin to make it easier to create the SQS queue.

Cheers!

**Comment by erezrokah** [comment]
Sorry for the late reply, I didn't saw the issue until now.
I just realised the link it to a private repository. 

Actually it should be easier to set up Lighthouse in Google Cloud Functions as they support chrome out of the box.

A lot has changed since I wrote the post and the layer now works with Node 10.
I'll try to update the post soon to reflect the changes and also post a new example with a public repository.
